### ISSUE TITLE
Corrigir folhas A3

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#110]

**Comment by luis242** [comment]
pampazada

**Comment by tsmurer** [comment]
tá dahora. mas se a gente acabar decidindo fazer frente e verso, precisamos nos atentar a botar uma pagina em branco depois de cada a3

**Comment by leaogui** [comment]
De acordo com o Tiago

**Comment by guga72** [comment]
está funcionando as folhas a3 dessa vez então tá mec.
