### ISSUE TITLE
Traduzir inglês-português + Arrumar palavras estrangeiras (Itálico)

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#111]
Palavras com tradução plausível devem ser traduzidas. Diferente disso, devem estar em itálico. Siglas também devem possuir a tradução.

**Comment by AndreyLacerda** [comment]
Pampa.

**Comment by leaogui** [comment]
zika memo

**Comment by tsmurer** [comment]
aprovado

**Comment by guga72** [comment]
Nice rapaziada.
