### ISSUE TITLE
Arrumar referências + Fontes

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#112]
Corrigir as citações, fontes nas imagens (nossas e outras) e encontrar fontes melhores para sites estranhos (portal7)

**Comment by AndreyLacerda** [comment]
Obs: Os cenários estão sem Fonte por que não estarão mais presentes no documento como imagem, mas sim como texto.

**Comment by leaogui** [comment]
muito bom caralhudo

**Comment by guga72** [comment]
Tá safe rapaziada

**Comment by tsmurer** [comment]
aprovado

**Comment by luis242** [comment]
papinelson
