### ISSUE TITLE
Rearranjar estrutura do documento LaTex

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#114]
- Organizar ordem dos capítulos certinho

- Seção não pode ser nome do livro

- criar subseção pra explicar na definição de escopo

- manifesto ágil tem que vir antes de falar de scrum

**Comment by tsmurer** [comment]
aprovado

**Comment by leaogui** [comment]
aprovei

**Comment by guga72** [comment]
Safezada

**Comment by luis242** [comment]
de buenas
