### ISSUE TITLE
Refinar viabilidade financeira da aplicação

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#115]
- de que forma renda vai ser planejada

- como nois vai cobrar os maluco

**Comment by AndreyLacerda** [comment]
Além de escrever oq ele tinha pedido, juntei o capítulo da viabilidade financeira com a necessidade de escalabilidade. Todas essas mudanças devem ser revisadas.

**Comment by leaogui** [comment]
por mim ta pampa, no máximo discussão sobre o preço dos bang mas meio que já tivemos isso então ta safe

**Comment by guga72** [comment]
acho que tá safe.

**Comment by tsmurer** [comment]
aprovado

**Comment by luis242** [comment]
brabo.
