### ISSUE TITLE
Refinar segurança da aplicação

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#116]
- explicar na parte de segurança como serão armazenadas as senhas
- Artigos que citamos da LGPD nos anexos

**Comment by leaogui** [comment]
Por parte do Tiago tudo ok, só adicionei o MD5.

**Comment by guga72** [comment]
modifiquei umas coisinhas, mas parece que tá safe.

**Comment by luis242** [comment]
mucho bom. nosso advogado para merdas futuras.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas aqui. Pra mim ta pampa.
