### ISSUE TITLE
Refinar análise de concorrência

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#117]
- sympla na analise e no quadro

- mais funcionalidade no quadro

Se precisar, inverter o quadro (Linha - Funcionalidades / Coluna - Apps)

**Comment by guga72** [comment]
No quadro está mostrando somente as nossas funcionalidades, precisaria mostrar todas as funcionalidades, tanto as nossas quanto a dos concorrentes.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa.

**Comment by luis242** [comment]
brabo.

**Comment by guga72** [comment]
tá safe.

**Comment by leaogui** [comment]
pampiroca
