### ISSUE TITLE
Documentar processo de Continous Integration

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#12]

**Comment by AndreyLacerda** [comment]
@luis242 achei pika man, mas ainda falta explicar o processo inicial de CI que a gente pretende fazer. Vamo mandar email?, bloquear Deploy? como q vai ser?

**Comment by guga72** [comment]
Parece que tá tranquilo agora.

**Comment by AndreyLacerda** [comment]
ta suave
