### ISSUE TITLE
Organizar as responsabilidades em um quadro

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#120]
- Adicionar responsabilidades de desenvolvimento também (Front(Tiago) - Back(Guilherme) - BD(Gustavo) - QA(Andrey))

**Comment by AndreyLacerda** [comment]
@Pedrofreitas18 , o Aires tinha pedido pra ser um quadro só, e com marcação de X nas responsabilidades, mais ou menos parecido com o quadro de análise de concorrências. 

Pega esse quadro da análise de concorrência como referência, a única diferença é que nesse quadro aí ta marcado 'Sim' e 'Não', sendo que nesse de responsabilidades é marcar X.

**Comment by luis242** [comment]
pampa

**Comment by AndreyLacerda** [comment]
Corrigi umas paradas. Pra mim fechou.

**Comment by guga72** [comment]
Parece bom.

**Comment by tsmurer** [comment]
safe
