### ISSUE TITLE
Adicionar definição de RESTful na revisão de literatura

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#121]

**Comment by leaogui** [comment]
Se acharem meio cru ainda tem como complementar, mas perto do que tinha ali eu pensei em não colocar coisa pra cacete pq a maioria tinha pouca coisa, deem opinião e revisem pq com certeza eu deixei escapar algo

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Acho que dá pra complementar explicando como funciona o RESTful  e tals, pq, no final de contas, tu falou que foi uma maneira criada por Roy Fielding com alguns objetivos e tals, mas não firmou como funfa ou oq é em sí.

**Comment by guga72** [comment]
parece que tá safe.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas aqui. Pra mim ta pampa.

**Comment by tsmurer** [comment]
tá aprovado

**Comment by Pedrofreitas18** [comment]
aprovado tb
