### ISSUE TITLE
Documentar log do front

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#123]

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Acho que vai ter que dar uma completada. Em comparação ao log do back-end, o log do front ficou incompleto. Cita algumas dessas bibliotecas e explica o funcionamento desse serviço e das bibliotecas citadas.

**Comment by luis242** [comment]
achei bonzão. altereei um negócio q falava do Facade só, mas ta pamps.

**Comment by leaogui** [comment]
achei gostoso

**Comment by tsmurer** [comment]
tá aprovado

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas aqui. Pra mim ta pampa.
