### ISSUE TITLE
Refinar Introdução

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#124]

**Comment by tsmurer** [comment]
não tem nenhuma exigência na descrição do card, então não sei se algo pode ter sido negligenciado ou não. se não tiver mesmo, tá excelente. aprovado.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa.

**Comment by leaogui** [comment]
De acordo com o Tiago porem menos formal

**Comment by luis242** [comment]
brabo.

**Comment by guga72** [comment]
tá safe.
