### ISSUE TITLE
Ajustar introdução

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#128]
- Introdução. Sugestão. Tirar título 1.1 (próprio capítulo introdução já é a contextualização). Mercado cheio? Fonte. Mercado tá cheio do que? 
Quarto parágrafo: Segundo lavor e segue a vida.
Quinto parágrafo: "1928 festivais" por ano ou ao longo de 3 anos ou ao todo? Referência de tempo faltou.
Brasil com b minúsculo, problemas de português.
Sexto parágrafo: "Existem outras soluções, outras plataformas" Quais? Colocar entre parênteses exemplos.

- n precisa ter "no site do ministério"

- fazer uma revisão melhor

- Página 11:
Problematização. Para auxiliar na organização. Organização de que?
Quarto parágrafo: Menção à EventBrite. Só explicam no quinto parágrafo quem são a EventBrite.
Sexto Parágrafo: Confusão. "Não tá tendo liga" no texto.
Sétimo parágrafo: Outra possibilidade é fornecer suporte a segurança. Não é uma possibilidade é uma proposta nossa
Justificativas: Está fraca. A justificativa precisa ser melhorada. Ancorar justificativa no nosso diferencial.

- Citação do Jornal O Dia: Muitas referências de blog, jornal aberto... Problema: Confiabilidade dos dados. Recomenda-se utilizar journals ou livros

- isso inclui tanto eventos open bar quanto chash bar

- Análise de Concorrência
Quadro comparativo: "Feature" não, funcionalidade
Funcionalidades dos concorrentes que não teremos. Pq não teremos? Todos os concorrentes têm essa funcionalidade.
Landing page com logo do evento, com links pros ingressos, etc. já pode ser o suficiente

**Comment by Pedrofreitas18** [comment]
Alguns posicionamentos

Quinto parágrafo: "1928 festivais" por ano ou ao longo de 3 anos ou ao todo? Referência de tempo faltou. - retirei a informação dos 3 anos, só precisa saber dos 1928 e pronto

Sexto Parágrafo: Confusão. "Não tá tendo liga" no texto. 
- refiz o sexto e sétimo paragrafo em um parágrafo só.

Citação do Jornal O Dia: Muitas referências de blog, jornal aberto... Problema: Confiabilidade dos dados. Recomenda-se utilizar journals ou livros 
- substitui pela referencia do ministério do turismo, o Lavor e segue a vida

Funcionalidades dos concorrentes que não teremos. Pq não teremos? Todos os concorrentes têm essa funcionalidade.
- a única funcionalidade listada nessa situação é da "Divulgação online do evento" que dps de falar com o aires seria a Landing page, ou seja, no quadro foi para "sim" 

Landing page com logo do evento, com links pros ingressos, etc. já pode ser o suficiente 
- indiferente, ainda se trata de uma divulgação online, precisa mexer no escopo

**Comment by luis242** [comment]
Ajustar aquele bagulho do "1928 festivais"

**Comment by Pedrofreitas18** [comment]
revisei isso luis, coloquei de volta em revisão

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas (refiz a justificativa). Pra mim ta pampa agora.

**Comment by guga72** [comment]
Pampa.

**Comment by leaogui** [comment]
deitou

**Comment by tsmurer** [comment]
aprovado
