### ISSUE TITLE
Ajustar revisão de literatura

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#129]
- Página 16
Krush é uma mulher. Usar 'por Krush'

- Revisão de Literatura
Não foi tratado do Core Business: Controle de Estoque, Questão de Segurança em Eventos, etc.
RESTful, etc. ficaria melhor num glossário que numa revisão de literatura.
Na revisão de literatura todos os parágrafos têm que ter fonte. Alguns parágrafos não têm.
Não falar em "pontos", que é muito vago.
Tem formas melhores de citar o manifesto ágil. Referenciar com autores. Mais de 3 autores pode usar o "e tal".

**Comment by guga72** [comment]
Tá safe

**Comment by leaogui** [comment]
pimpa

**Comment by luis242** [comment]
seife.

**Comment by Pedrofreitas18** [comment]
tá ok
