### ISSUE TITLE
Documentar Critérios de segurança/privacidade

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#13]

**Comment by AndreyLacerda** [comment]
Ae @tsmurer , acho que ficou um pouco solto. Coloca uma introdução para cada tópico, informando o pq tem que levar isso em consideração no nosso projeto. Do jeito que tá, tu explica bem a LGPD e qual parte importa pra gente, mas não o pq.

Outra coisa tbm, não pode ter espaço em branco entre o capítulo e as seções . Coloca uma introdução ao capitulo nesse espaço.

Última coisa, aspas no LaTex não é "exemplo", mas sim ``exemplo''.

**Comment by AndreyLacerda** [comment]
@tsmurer , agora ta melhor. Arrumei só algumas paradinhas, mas acho que ta faltando falar quais são os ativos que, a priore, a gente precisa defender no sistema.

**Comment by AndreyLacerda** [comment]
Boa, por mim ta pronto.

**Comment by leaogui** [comment]
acho que ta bom mas a gente vai ter que voltar nesse bagulho ao decorrer

**Comment by guga72** [comment]
Pra mim ta safe

**Comment by luis242** [comment]
escreve bem e é gostoso. aprovado.
