### ISSUE TITLE
Ajustar planejamento do projeto

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#130]
- Página 20
"Estruturar metodologia". Utilizamos metodologia, e não estruturar. Estruturar metodologia dá a ideia de criar uma metodologia.
Não coletar dados de blogs.

- Sobre o ZenHub: Dizer que utilizaremos o ZenHub antes de sair descrevendo.
Feito e Closed: Distinção não ficou clara.
Trello: Falamos da ferramenta antes de dizer que utilizaremos. Mesmo que o ZenHub.

- Novamente. Não utilizar a palavra "ponto" para o que ela está sendo utilizada (ex. "Neste ponto")

Distinção com COVID-19 ou sem COVID-19. o Braz achou que não faz muita diferença. "Por conta das suspensões, foram feitas as seguintes adaptações..." e esclarecer

Descrição do TDD e BDD: Esses itens deveriam estar no capítulo 2, revisão de literatura, pois trata-se só de teoria, e não da utilização.

- Página 25

Quadro 2. Só o Andrey e o Guilherme com responsabilidades sobre o repositórios. O ideal é que todos postem. Colocar responsabilidade de revisão de postagem.
"O projeto será gerido em cima do framework" não utilizar o termo "em cima" desta forma
3.4.1: "Adaptações foram feitas em cima do SCRUM" nós adaptamos SCRUM ao nosso projeto.
Os Sprints não foram acrescidos ao projeto. Os Sprints fechados precisam ser colocados.

- Página 26

3.4.3.1: Informações que já foram colocadas no item 3.1.1. (ZenHub, Trello)
Burndown e Burnup: Tem definição mas não tem os gráficos em si. Mesma coisa o cumulative flow.

- TDD deveria colocar no capitulo 2

- quadro 2 está meio ruim
ver a parte de revisão dos repositórios e talvez separar no SVN e github
condenador tem que especificar e quem vai ser os subordinados tem que falar
colocar todo mundo no quadro nn somente o responsável
colocar no texto isso os professores são cliente
nn product owner

**Comment by guga72** [comment]
Pra mim tá pampa.

**Comment by leaogui** [comment]
pra mim ta bom, vou revisar o documento geral mesmo ai se tiver alguma coisa, mudo lá

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa
