### ISSUE TITLE
Ajustes Gerais às Correções na Apresentação de 14.04

### ISSUE THREAD

**Issue by tsmurer** [Projeto-Integrado-2020/Pachanga#131]
Arrumar Pt-br

Substituir o uso do termo "ponto" por palavras mais adequadas quando cabível (sugestões: "Aspecto", "Assunto", "Tema", etc.).

Adequação do tempo dos verbos no futuro que se referem a fatos passados ou presentes.

Closed: itálico

**Comment by leaogui** [comment]
Lendo o documento todo a gente acha alguns problemas, como o "despor" que eu citei no discord, e mesmo revisando várias vezes pode ser que algo tenha escapado, caso leiam e achem algum erro de pt-br, por favor avisem/ajustem

**Comment by Pedrofreitas18** [comment]
Referente aos pontos, parece ok

3.4 Gestão de Tempo - "Além disso, algumas ferramentas de controle de tempo serão utilizadas para auxiliar
na gestão do projeto.", já não estamos utilizando?. 

Em também 3.4.1 Formato de Sprint, encontrei alguns verbos no futuro, como "Todos esses eventos serão realizados online, via Discord", já não estamos realizando?   

3.4.3 Ferramentas de Controle - "alguns recursos serão
", não estamos usando os gráficos já?

**Comment by AndreyLacerda** [comment]
Ok

**Comment by tsmurer** [comment]
Ok

**Comment by luis242** [comment]
salvok

**Comment by guga72** [comment]
safe
