### ISSUE TITLE
Ajustar arquitetura e tecnologia

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#132]
- Página 31

Quarto Parágrafo. VMWare como referência ao Spring Initializr. Braz não conseguiu abrir a referência. Link quebrado?
Foi citado VMWare. SpringIO seria melhor.

**Comment by leaogui** [comment]
o initializr é pesado, por isso não abre, a citação eu arrumei

**Comment by AndreyLacerda** [comment]
Revisei lá. Coloquei o link original mesmo, fazer oq... Pra mim ta pampa.

**Comment by luis242** [comment]
eu como seu cu em forma de aprovação :)

**Comment by guga72** [comment]
Tá safe.

**Comment by tsmurer** [comment]
Tá safe
