### ISSUE TITLE
Ajustar viabilidade financeira e escalabilidade

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#133]
- Página 70

Viabilidade Financeira da Aplicaçã (6.1). Isso está ligado à definição de escopo, forma de cobrança. Surgiram dúvidas sobre o modelo de negócio (coisa pra pensar). Diminuir porcentagem é um diferencial, mas precisa estar alinhado com os custos. A ser pensado.
Muito cedo pra definir valores!
Usuário premium pagar só pelos relatórios. Dúvida: Será que o principal diferencial é o controle de estoque e segurança. O que levaria alguem a pagar pelos relatórios? Pq pagar já que estou recebendo uma porcentagem dos ingressos.

- Página 71

Explicação dos Dynos ficariam melhor numa nota de roda-pé.

- Página 73

"Com esta tabela..." referencia >À FIGURA 14<.

Arrumar figura (não pode deixar espaço em branco entre a figura e o texto)

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa.

**Comment by leaogui** [comment]
Arrumei uns tchurusbango, ta bom pra mim

**Comment by luis242** [comment]
pampapampapampapampa.

**Comment by Pedrofreitas18** [comment]
pampa
