### ISSUE TITLE
Ajustar apêndices

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#134]
- Página 93

- mudar o dicionário de dados

- fazer as tabelas em vez de deixar figuras

- colocar essa tabela geral no final do apêndice do dicionário

- lgpd pode mudar

- caso mude tem que atualizar no documento

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by leaogui** [comment]
pelo que eu vi ta pampa

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by tsmurer** [comment]
aprovado
