### ISSUE TITLE
Ajustar definição de escopo

### ISSUE THREAD

**Issue by leaogui** [Projeto-Integrado-2020/Pachanga#138]
- Página 33

Controle de Segurança. Gerou dúvidas. 1: Quem vai dar o alerta de segurança? Qualquer usuário? Quem tem esse poder. 2: Dica: Histórias de usuário e cenários em apêndices. Product Backlog também

**Comment by AndreyLacerda** [comment]
Pampa.

**Comment by guga72** [comment]
tá safe.

**Comment by leaogui** [comment]
zika

**Comment by tsmurer** [comment]
aprovado
