### ISSUE TITLE
Ajustar Diagrama de Atividades

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#139]
- Página 56

Diagramas de Atividade. Primeiro diagrama. É recomendável que as atividades estejam no infinitivo (ex. "acessar", etc.). Leitura é da esquerda para direita, usuário de estoque está a direita. "Aumenta a quantidade de produto"? Faltou condição no meio, tá esquisito.

- Página 57

Alerta de segurança. Quem é? Precisa escrever melhor.

- Página 59

Loop infinito no diagrama de atividades. Integra ou entrega do google forms? "Valida o formulário, tudo certo? Volta" (loop infinito).
"Página 59 mesma coisa"

- Página 60

Venda de Ingressos. Para comprar ingresso já não tenho que estar logado ou cadastrado? E se eu já estiver cadastrado? O diagrama de atividades não está representando essa situação

Página 93

Diagramas de atividades com 2 finais. O recomendável é ter um início e um fim.

**Comment by guga72** [comment]
Coloquei o card aqui para todo mundo revisar os diagramas de atividade que estão no google drive, ainda não tirei as fotos para talvez não precisar ficar fazendo várias vezes isso. Todo mundo recebeu um e-mail sobre isso, começa na terceira tela os dois primeiros tem relação com o diagrama de classes a partir deles estão os diagramas que deveriam ser modificados.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Só acho que vai ter que resumir o diagrama de venda de ingressos, pq não vai caber na folha. Tirando isso, pra mim ta pampa.

**Comment by tsmurer** [comment]
aprovado

**Comment by leaogui** [comment]
tentei arrumar uns bagulho por visual e quase caguei sadjaslk, ta zika

**Comment by luis242** [comment]
pampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampapampa

**Comment by luis242** [comment]
ta pampa fi

**Comment by AndreyLacerda** [comment]
Pampa mans

**Comment by tsmurer** [comment]
tá adequado

**Comment by leaogui** [comment]
de acordo
