### ISSUE TITLE
Ajustar MER / DER

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#140]
- Página 63

MER. Dúvidas esclarecidas.

Ingresso e lote. Relação é 1 pra N onde um lote pode ter vários ingressos. Como atributo de lote vc tem código de ingresso. Ingresso precisa ter código do lote e não o inverso.
Nomenclaturas: Festa e Questionário. A festa cria o questionário forms? O nome do relacionamento não está adequado. Verbo "criar" ficou estranho pq quem cria é pessoa.

Tirar atributos e tabelas intermediárias do MER

**Comment by AndreyLacerda** [comment]
Pampa.

**Comment by guga72** [comment]
Parece que está certo

**Comment by leaogui** [comment]
ta uma mer/der, brinks ficou lindo bebe

**Comment by tsmurer** [comment]
aprovado
