### ISSUE TITLE
Alterar referências de blogs

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#141]
ter cuidado com referências duvidosas de blogs etc. sempre buscar referências de jornals

**Comment by tsmurer** [comment]
tô botando pra revisão pra saber da opinião de vocês quais referências deveriam ser substituídas. eu deixei a da forbes pq eu acho que o ayres tinha falado que a forbes é aceitável pra esse tipo de informação.

**Comment by leaogui** [comment]
A referência de burndown/up;
 visão geral sobre metodologia ágil;  
Como os eventos musicais movimentam o turismo no país;
Abordando a arquitetura MVC, e Design Patterns: Observer, Composite, Strategy.

Acho que esses se pá

**Comment by tsmurer** [comment]
"a referência de burndown/up é para uma imagem" é fonte de figura
"visão geral sobre metodologia ágil" tá substituído
"como os eventos musicais movimentam o turismo no país" a fonte é site oficial do governo
"Abordando a arquitetura MVC, e Design Patterns: Observer, Composite, Strategy." to trabalhando nesse aqui

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by leaogui** [comment]
ziko

**Comment by guga72** [comment]
safe

**Comment by luis242** [comment]
fechastes
