### ISSUE TITLE
Desenvolver "Hello World" do Front

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#147]

**Comment by tsmurer** [comment]
TL;DR: Qual o caminho da raiz até o node_modules vocês acham ideal? Resumo da discussão abaixo.

Pessoal, eu subi no github o projeto do front-end. @leaogui acho q vc em especial vai querer dar uma olhada. Dei um "ng new front-end" na raiz do projeto pra criar o diretório do front-end, ou seja: O projeto do Angular ficou com nome "front-end", que é o nome do diretório.

Eis o dilema, meu estimado:

*Inicialmente o Andrey propôs que o projeto do Angular ficasse dentro do diretório front-end, levando Pachanga no nome do projeto, e dentro desse projeto o node_modules e a porra toda ("~/front-end/cliente-pachanga/node_modules").

*O problema é q isso acaba gerando uma complexidade desnecessária de diretórios. Em tese o diretório "front-end" não vai mais nada além do projeto do cliente em si.

**Comment by tsmurer** [comment]
![2020-04-23_19-05-25.jpg](https://images.zenhubusercontent.com/5e6e9f3b8ec11b395dec17da/a76caad5-ece3-4392-9d10-8ed01a91db50)

página default gerada no localhost:4200 com o "ng serve"

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa.

**Comment by luis242** [comment]
safe, corrigi uma coisita

**Comment by leaogui** [comment]
hello, pachanga

**Comment by guga72** [comment]
safe
