### ISSUE TITLE
Desenvolver "Hello World" do Back

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#148]

**Comment by Pedrofreitas18** [comment]
desenvolvimento_back_end.tex tem um breve resumo do que foi feito. O código em si já esta no heroku e git

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Ta pampa pra mim agora.

**Comment by guga72** [comment]
safe

**Comment by luis242** [comment]
brabo

**Comment by leaogui** [comment]
zika
