### ISSUE TITLE
Documentar Cenários de cada user story

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#15]

**Comment by tsmurer** [comment]
https://cucumber.io/docs/gherkin/reference/

**Comment by tsmurer** [comment]
Acabei de adicionar um pouco de conteúdo, subi pro SVN e joguei pra revisão, mas eu acho que o desenvolvimento de cenários é algo que vai ser feito continuamente ao longo do projeto conforme a gente encontrar novos problemas e soluções.
A versão atual eu acredito que esteja pronta pra uma primeira revisão, mas esse card eu acho que não fica concluído em definitivo até o fim dos testes end-to-end.

**Comment by AndreyLacerda** [comment]
Está dahora, acho que está certinho, mas faltou a feature de vender ingressos pela Pachanga. Escrevendo essa feature e os cenários, por mim ta pronto.

**Comment by tsmurer** [comment]
Acabei de escrever a feature de vender ingressos com base no que foi definido pelo diagrama de atividades. Podem checar se está correto?

**Comment by AndreyLacerda** [comment]
Isso mesmo man. Pra mim ta feito.

**Comment by leaogui** [comment]
fino

**Comment by Pedrofreitas18** [comment]
por mim ok

**Comment by guga72** [comment]
Parece que tá safe.
