### ISSUE TITLE
Melhorar Revisão de Literatura da Gestão de Eventos (Core)

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#168]

**Comment by Pedrofreitas18** [comment]
Eu usei \begin{itemize} \item \end{itemize} em certo ponto, não me pareceu excessivo pois eu estava fazendo uma enumeração, mas qualquer coisa posso mudar de boas.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta show. Não é POSSIVEL que eles vão reclamar de novo.

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
brabo d+

**Comment by tsmurer** [comment]
beleeezzzz
