### ISSUE TITLE
Corrigir mensagem de erros no form de cadastro

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#170]

**Comment by AndreyLacerda** [comment]
Ae @tsmurer, não tem como o espaço entre os campos aumentar só quando o erro aparecer? Da forma que tá, ficou um espaço muito grande entre as senhas.

Tem que documentar tbm, como 'Desenvolvimento Front-end' - "Correções pós Apresentação da Prova de Conceito".

**Comment by AndreyLacerda** [comment]
Revisado. Pra mim ta pamps

**Comment by guga72** [comment]
Tá safe.

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by luis242** [comment]
pamps
