### ISSUE TITLE
'Diagrama de Gantt' para decidir próximos passos

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#172]

**Comment by AndreyLacerda** [comment]
[https://app.zenhub.com/files/247109099/d9652e73-13aa-40e2-a4d4-669ea01f7843/download](https://app.zenhub.com/files/247109099/d9652e73-13aa-40e2-a4d4-669ea01f7843/download)

**Comment by Pedrofreitas18** [comment]
Alguns pontos: 
- Não seria necessário incluir um artefato para testes?
- Referente ao tempo: não dava para gerar um png ou jpeg a partir do excell? Embora eu ache bem ok a duração de cada artefato por hora.
- Acho que precisamos de um artefato para a configuração uma caixa de e-mail da aplicação.

**Comment by AndreyLacerda** [comment]
Sobre os pontos:

- Teste não precisa de artefato pq prometemos fazer TDD, então toda funcionalidade já deve ser feita com testes primeiro.
- Até dá pra gerar PNG e JPEG, mas ficou muito feio. Vou tentar de novo.
- Configuração de caixa de e-mail seria parte da funcionalidade que envia email, então não precisa de artefato, por criar mais dependência entre tarefas do que já tem. Provavelmente a gente vai dividir isso na hora, mas pro Gantt, acho que não precisa.

**Comment by tsmurer** [comment]
carai, tá dahora. eu acho que é isso aí mesmo.

**Comment by AndreyLacerda** [comment]
[https://app.zenhub.com/files/247109099/df7f01ae-620d-4785-a4a2-96a98488ec24/download](https://app.zenhub.com/files/247109099/df7f01ae-620d-4785-a4a2-96a98488ec24/download)

**Comment by luis242** [comment]
pamps

**Comment by AndreyLacerda** [comment]
[https://app.zenhub.com/files/247109099/c9ebd0c2-2c5b-4373-ba7a-619f4a44ca78/download](https://app.zenhub.com/files/247109099/c9ebd0c2-2c5b-4373-ba7a-619f4a44ca78/download)

**Comment by Pedrofreitas18** [comment]
bufadona essa versão. Em termos de apresentação, o mais simples  é mais visual, para nosso uso, esse novo é mais completo

**Comment by guga72** [comment]
tá pika pra caralho.
