### ISSUE TITLE
Desenvolver tela de perfil do usuário

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#183]

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by luis242** [comment]
A igualdade de oportunidades para homens e mulheres é um princípio essencial da democracia.
Quero dizer que meu olhar não é para o PIB e para os juros, é para as pessoas.
É verdade: eu sou uma mulher dura cercada de homens meigos.
Não acho que quem ganhar ou quem perder, nem quem ganhar nem perder, vai ganhar ou perder. Vai todo mundo perder.
Eu vi. Você, veja... Eu já vi, parei de ver. Voltei a ver, e acho que o Neymar e o Ganso têm essa capacidade de fazer a gente olhar.
Nós acreditamos que, sempre, em qualquer situação, é muito melhor o diálogo, o consenso e a construção democrática do que qualquer outro tipo de ruptura institucional.
Nós não vamos colocar uma meta. Nós vamos deixar uma meta aberta. Quando a gente atingir a meta, nós dobramos a meta.
Eu já entendi que você entende, pois se você não tivesse entendido não entenderia que você teria entendido para ser explicado antes de você entender.
Na vida a gente não sobe de salto alto.
Não acho que quem ganhar ou quem perder, nem quem ganhar nem perder, vai ganhar ou perder, vai todo mundo perder.
Paes é o prefeito mais feliz do mundo, que dirige a cidade mais importante do mundo e da galáxia. Por que da galáxia? Porque a galáxia é o Rio de Janeiro. A via Láctea é fichinha perto da galáxia que o nosso querido Eduardo Paes tem a honra de ser prefeito.
Não acredito que tenha alguém acima da corrupção. Acho que todo mundo pode cometer corrupção.
Quero dizer para vocês que, de fato, Roraima é a capital mais distante de Brasília, mas eu garanto para vocês que essa distância, para nós do Governo Federal, só existe no mapa. E aí eu me considero hoje uma roraimada, roraimada, no que prova que eu estou bem perto de vocês.
É só fazer um raciocínio: temos eleições a cada dois anos no Brasil. Tudo o que o governo fizer é campanha eleitoral.
O presidente Lula me deixou um legado, que é cuidar do povo brasileiro. Eu vou ser a mãe do povo brasileiro.
Um grande varejista uma vez disse o seguinte, disse uma coisa muito simples e de fácil entendimento, que é muito difícil para o conjunto da população ou para muitas camadas da população, comprar à vista, mas que quando se compra a prazo, tudo fica mais viável.
Meu compromisso é honrar as mulheres, proteger os mais frágeis e governar para todos.
Quando acontece alguma coisa errada no meu governo, eu fico triste.
Nós convivemos com a democracia. E quem tem democracia quer sempre mais democracia.
Posso ter cometido erros, mas não cometi nenhum crime.

**Comment by guga72** [comment]
safe.
