### ISSUE TITLE
Desenvolver armazenamento do log do back em arquivo-texto

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#194]

**Comment by guga72** [comment]
foi feito alteração no sistema de log, que tinha sido escrito na manutenibilidade da aplicação e no sistema de log do back.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas coisas. Pra mim ta pampa agora.

**Comment by luis242** [comment]
pampa

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by tsmurer** [comment]
ok
