### ISSUE TITLE
Refinar sistema de cadastro/login pelo Facebook

### ISSUE THREAD

**Issue by guga72** [Projeto-Integrado-2020/Pachanga#2]
No momento de cadastrar ou de logar deve ser possível usar a API do facebook para realizar tal tarefa.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa agora.

**Comment by luis242** [comment]
safe

**Comment by tsmurer** [comment]
belezura
