### ISSUE TITLE
Construir Tela Menu de Festas do Usuário

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#216]

**Comment by Pedrofreitas18** [comment]
Cara, ficou muito bonito, mesmo. Eu percebi que a responsividade está um pouco estranha, não só nessa página, mas no site como todo. Vou falar sobre isso com mais detalhes na daily.

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pampa

**Comment by tsmurer** [comment]
okk
