### ISSUE TITLE
Finalizar Painel de Festa

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#224]

**Comment by luis242** [comment]
não incrementei nada na documentação por achar que não há necessidade, visto que, quando documentei a página, ele explica as funcionalidades do service q foi criado. caso achem necessário, posso escrever seguindo suas orientações.

**Comment by AndreyLacerda** [comment]
Já adicionei umas paradas a mais. Pra mim ta pampa agora.

**Comment by guga72** [comment]
safe

**Comment by Pedrofreitas18** [comment]
pamps

**Comment by tsmurer** [comment]
okk
