### ISSUE TITLE
Adiantar controllers de convite de membro colaborador

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#227]
Recebe uma lista de emails. Caso o e-mail já esteja registrado na Pachaga, adicionar o usuário direto na festa. Caso o e-mail não esteja cadastrado na Pachanga, enviar um e-mail pedindo para cadastrar + já auto vincular o usuário na Festa assim que o cadastro é realizado.

**Comment by guga72** [comment]
tem tanto na parte do mvp do back-end quanto dos patterns utilizados.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pamps agora.

**Comment by luis242** [comment]
pamp

**Comment by tsmurer** [comment]
okk

**Comment by Pedrofreitas18** [comment]
pamps
