### ISSUE TITLE
Aprimorar controladores de grupo/permissão

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#254]
-- Get de todas as permissões x

-- Add Grupo (nomeGrupo, List(codPermissao), codFesta) x

-- Edit Grupo (nomeGrupo, List(codPermissao), codGrupo) x

-- remover grupo (codGrupo, idUserExecutor), fazer as validações (nao pode remover grupo com gente, ou grupo 'ORGANIZADOR') x

-- remover membro (idMembroRemovido, codGrupo, idUserExecutor), se for o organizador nn pode sair do grupo organizador x

-- Edit usuario Grupo (idCara, List(IdGrupo) idGrupoAtual, idUserExecutor)

-- Edit usuario Grupo de várias pessoas ao msm tempo (idGrupo, List(IdUsuario), idUserExecutor), adicionar todo mundo da lista e quem não tiver na lista tirar do grupo

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by tsmurer** [comment]
okk

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pamp
