### ISSUE TITLE
Corrigir documentação seguindo pontos levantados em reunião (04/08/2020)

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#257]
- Folhas A3 no final do capítulo

- Atribuição de pontos - Tabela e não quadro

- Coluna de Executor nos quadros de Sprints

- Arrumar pontuação atribuída aos integrantes

- Tabela de atribuição por equipe

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pamps

**Comment by leaogui** [comment]
pampa

**Comment by Pedrofreitas18** [comment]
pampa
