### ISSUE TITLE
Desenvolver controladores de produto de estoque

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#265]

**Comment by AndreyLacerda** [comment]
Obs: Todos os métodos recebem o codUsuario por parâmetro para devidas validações

- addProduto: Método recebe o JSON do produto (Nome, Preço, quantidade atual, quantidade máxima, porcentagem mínima) pelo Body e o codEstoque pelo Param. Este método vai criar um instância de Produto e de Produto_x_Estoque;

- removerProduto: Recebe o codProduto e o codEstoque por parametro. Deleta a instancia de Produto_x_Estoque e Produto;

- editarProduto: Método recebe o JSON do produto (Nome, Preço, quantidade atual, quantidade máxima, porcentagem mínima) pelo Body, o codProduto e o codEstoque por Param. Este método atualiza a instancia de Produto e Produto_x_Estoque caso algo tenha sido alterada;

- baixaProduto: Recebe o codProduto, codEstoque e o valor da baixa por param. Decresce o valor à quantidade atual do Produto_x_Estoque;

- recargaProduto: Recebe o codProduto, codEstoque e o valor da recarga por param. Acrescenta o valor à quantidade atual do Produto_x_Estoque;

* Atualizar o get de estoque, adicionando o retorno do produto com todas as informações do Produto e do respectivo Produto_x_Estoque.

**Comment by luis242** [comment]
pampa e revisado

**Comment by guga72** [comment]
safe.

**Comment by AndreyLacerda** [comment]
Revisado e Pamps

**Comment by tsmurer** [comment]
pamps
