### ISSUE TITLE
Correção de bugs do back-end ao atribuir permissão

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#280]
Ao criar mais de um grupo de permissão e colocar o mesmo cara:

- Não dá pra deletar mais nada

- Não dá para acessar estoque

- Usuários repetidos no FestaTO.Usuarios

**Comment by leaogui** [comment]
22/08 - Problemas de festa/usuários repetidos em todos os lugares resolvidos, festa deletando produto_x_estoque, estoque e produto, e não reclama mais ao deletar, mas ainda tem erro de "query retorna 2 valores no getfesta"

23/08 - Gustavo resolveu o problema da query
