### ISSUE TITLE
Iniciar melhoria de responsividade das telas

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#294]
- Tela inicial
- Cadastro/Login
- Perfil
- Editar perfil

**Comment by tsmurer** [comment]
A quem revisar: Considerar "painel da festa" no lugar de "editar perfil"

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by guga72** [comment]
zika pra caralho, pode abaixar as calças tiago que hj eu vou te mamar seu gostoso.

**Comment by leaogui** [comment]
eu mamo junto

**Comment by Pedrofreitas18** [comment]
pampa
