### ISSUE TITLE
Documentar Sprint 21 e atualizar blogs, Gantt e métrica

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#298]

**Comment by tsmurer** [comment]
okk

**Comment by luis242** [comment]
pampa

**Comment by leaogui** [comment]
Do you remember the 21st night of September?
Love was changing the minds of pretenders
While chasing the clouds away
Our hearts were ringing
In the key that our souls were singing
As we danced in the night
Remember how the stars stole the night away
Hey hey hey
Ba de ya, say do you remember?
Ba de ya, dancing in September
Ba de ya, never was a cloudy day
Ba duda, ba duda, ba duda, badu
Ba duda, badu, ba duda, badu
Ba duda, badu, ba duda
My thoughts are with you
Holding hands with your heart to see you
Only blue talk and love
Remember how we knew love was here to stay
Now December found the love we shared in September
Only blue talk and love
Remember true love we share today
Hey hey hey
Ba de ya, say do you remember?
Ba de ya, dancing in September
Ba de ya, never was a cloudy day
And we say
Ba de ya, say do you remember
Ba de ya, dancing in September
Ba de ya, golden dreams were shiny days
The bell was ringing, oh oh
Our souls were singing
Do you remember? never a cloudy day, yow
And we say
Ba de ya, say do you remember?
Ba de ya, dancing in September
Ba de ya, never was a cloudy day
And we say
Ba de ya, say do you remember?
Ba de ya, dancing in September
Ba de ya, golden dreams were shiny days
Ba de ya de ya de ya
Ba de ya de ya de ya
Ba de ya de ya de ya de ya
Ba de ya de ya de ya
Ba de ya de ya de ya
Ba de ya de ya

**Comment by guga72** [comment]
safe.
