### ISSUE TITLE
Travar recarga/baixa em festa diferente de iniciada

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#299]

**Comment by guga72** [comment]
Faltou teste do validarFestaInicializada.

**Comment by leaogui** [comment]
pode crer, esqueci

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by AndreyLacerda** [comment]
EDIT: Ao editar produto_x_estoque com festa iniciada, não deve ser possível editar a quantidade atual

**Comment by leaogui** [comment]
EDIT: Adicionada a funcionalidade, faltou 1 linha que não consegui testar, quando tiver contato com o Gustavo vejo como isso funciona, mas é só 1 linha

**Comment by luis242** [comment]
pampa

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by guga72** [comment]
safe.
