### ISSUE TITLE
Refinar Sistema de Cadastro/Login pelo Google

### ISSUE THREAD

**Issue by tsmurer** [Projeto-Integrado-2020/Pachanga#3]
No momento que o usuário tentar entrar ou se cadastrar na aplicação deve poder fazer isso pela API do Google.

**Comment by guga72** [comment]
https://www.youtube.com/watch?v=hlWk2QWew50

**Comment by AndreyLacerda** [comment]
Revisei e corrigi umas paradas. Pra mim ta pampa agora.

**Comment by Pedrofreitas18** [comment]
safe

**Comment by luis242** [comment]
brabo

**Comment by tsmurer** [comment]
ta pombas tb
