### ISSUE TITLE
Ajustar responsividade das telas de festa

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#301]
- Criar/Editar Festa
- Painel Festa
- Painel de grupo
- Painel de Estoque
- Painel de Produto

**Comment by tsmurer** [comment]
não consegui implementar a trava da orientação da tela de estoque em paisagem e não sei mais se é possível.
eu posso colocar um aviso de recomendação qqr coisa se a orientação estiver em retrato, eu acho que é até melhor prática. 
no mais, acredito que essas telas não vão quebrar, mas testem aí.

**Comment by luis242** [comment]
pamps

**Comment by AndreyLacerda** [comment]
Pampa

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by guga72** [comment]
safe.
