### ISSUE TITLE
Explicar falta de gerenciamento de fornecedores

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#322]

**Comment by tsmurer** [comment]
A explicação está no capítulo de definição de escopo. Colem "Em apresentação do Produto Mínimo Viável" no Ctrl + F para encontrar.

**Comment by luis242** [comment]
pampa

**Comment by AndreyLacerda** [comment]
Movi pra parte de Controle de Estoque mesmo

**Comment by leaogui** [comment]
pamp

**Comment by guga72** [comment]
safe.
