### ISSUE TITLE
Aprimorar documentação sobre funcionalidade de relatórios

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#328]

**Comment by guga72** [comment]
Modificação na definição de escopo dos tipos de relatórios da nossa aplicação e pq eles são úteis.

**Comment by AndreyLacerda** [comment]
Acho q deu uma bugada na parada. Ta um paragrafo de umas 20 linhas, e o segundo paragrafo é uma repetição do inicio do primeiro. Fora isso, o commit do SVN saiu com o link do zenhub por algum motivo.

**Comment by AndreyLacerda** [comment]
Revisado e pamps

**Comment by leaogui** [comment]
pamp

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa
