### ISSUE TITLE
Aprimorar explicação sobre Logs front-end e back-end

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#333]

**Comment by guga72** [comment]
Foi feito mudanças na manutenibilidade da aplicação falando como está foi usado os logs, mais a maior quantidade de detalhes deixei para ficar na parte do desenvolvimento do mvp que parecia que fazia mais sentido.

**Comment by AndreyLacerda** [comment]
Revisado e Pamps

**Comment by leaogui** [comment]
pamp

**Comment by luis242** [comment]
pampa

**Comment by Pedrofreitas18** [comment]
pampa
