### ISSUE TITLE
Ajustar comentários apontados pelo avaliador Léo

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#342]

**Comment by leaogui** [comment]
erros de português arrumados, parágrafos que ele pediu arrancados, notas de rodapé em andamento

**Comment by leaogui** [comment]
Talvez editar alguns diagramas de atividade
Alteração nos diagramas do BD (acredito que já feitas)
Alterações restantes: virar prints para folha A3 (necessário?)
Considerações finais após as métricas

**Comment by tsmurer** [comment]
cara, falta corrigir a mesma coisa que no meu, que é a demonstração da viabilidade financeira. No caso o leo motta anotou que "A aplicação Pachanga tem total capacidade financeira" é uma presunção "ao quadrado". em outras palavras, falta demonstração.

**Comment by leaogui** [comment]
eu tinha alterado isso na real, tirei que tem total capacidade financeira mas não coloquei demonstração tb, vou olhar o seu

**Comment by AndreyLacerda** [comment]
Revisado e Pamps.

**Comment by tsmurer** [comment]
okk

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pampa

**Comment by Pedrofreitas18** [comment]
pampa
