### ISSUE TITLE
Iniciar desenvolvimento de Controllers e Services de Ingressos

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#379]
- Add get por festa

**Comment by leaogui** [comment]
os testes sumiram pq sei lá ??? depois que estourou o poste aqui, mas só refazer os testes, tanto que os mocks n sumiram, só algumas coisas que eu fiz por ultimo

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pamps

**Comment by AndreyLacerda** [comment]
Pamps
