### ISSUE TITLE
Desenvolver convite de funcionários

### ISSUE THREAD

**Issue by guga72** [Projeto-Integrado-2020/Pachanga#38]
Poderá invitar outros usuários para participar da sua festa através do e-mail, podendo escolher grupos para o inserir ou colocando individualmente, caso seja individual tem que adicionar as permissões para ele, e o e-mail de que será enviado pode ser escolhido pelo administrador.

**Comment by tsmurer** [comment]
https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mail.html
