### ISSUE TITLE
Aprimorar áreas e problemas de segurança

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#383]
- Atualizacao de problemas em tempo real
- Adição do campo de descrição de problema no form de "relatar problema" (descricao_prob)
- Adição de campo de observação ao Marcar problema como Feito/Engano (obs_solucao)
- Ao reabrir problema, informar nova descrição (obrigatório - descricao_prob)

**Comment by guga72** [comment]
parece safe.

**Comment by AndreyLacerda** [comment]
Revisado, corrigido e pamps.

**Comment by leaogui** [comment]
boa

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by luis242** [comment]
pamps
