### ISSUE TITLE
Finalizar back-end de Ingressos

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#384]
- Criar ingressos através de uma lista enviada pelo front-end
- Alteração de status e horário_fim de ingresso no Check-in
- Alteração de status de compra

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by guga72** [comment]
safe.

**Comment by AndreyLacerda** [comment]
Pampas

**Comment by luis242** [comment]
pamp
