### ISSUE TITLE
Adicionar campos descricao_prob e obs_solucao na "Area_Seguranca_x_Problema" e criar tabela de histórico

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#388]
- Adicionar no banco de dados campos para descricao_prob e obs_solucao (alterar documentacao)
- Adicionar campos nos controladores e serviços de "Area_Seguranca_x_Problema"
- Adicionar tabela de histórico de "Area_Seguranca_x_Problema" (registro criado à cada alteração de status)

**Comment by AndreyLacerda** [comment]
Documentação revisada, corrigida e pamps.

**Comment by luis242** [comment]
pamps

**Comment by leaogui** [comment]
samps

**Comment by tsmurer** [comment]
revisado
