### ISSUE TITLE
Desenvolver telas de preenchimento e check-out de ingressos

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#389]
- Lembrar do cupom de desconto

**Comment by luis242** [comment]
- Rapaziada, por enquanto não tem como acessar a página de checkout pelo botão de compra de ingressos. Ainda não desenvolvi como serão passados as informações das quantidades de ingressos e de quais lotes eles pertencem para a página de checkout.

http://localhost:4200/salveeeeee&1/venda-ingressos/venda-checkout

Esse é um exemplo de link que leva à página de checkou. Basta adicionar "/venda-checkout" no final da URL.

**Comment by AndreyLacerda** [comment]
Revisado e pamps. Se mais alguem estiver com a data bugada, é por que, por algum motivo, a data já está vindo certo agora.

**Comment by leaogui** [comment]
meio bugado mas pampa

**Comment by guga72** [comment]
safe.

**Comment by tsmurer** [comment]
okk
