### ISSUE TITLE
Desenvolver Tela de "Meus Ingressos"

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#394]
Tipo Sympla
- Ativos/Encerrados
- Clicar no banner leva à tela de compra de ingressos
- Botao para imprimir ingresso
- Botao para visualizar QRCode (Abrir um dialog com o código QR)

**Comment by guga72** [comment]
safe.

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by AndreyLacerda** [comment]
Pamps.

**Comment by luis242** [comment]
pamps
