### ISSUE TITLE
Aprimorar tela de "Meus Ingressos"

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#427]
- Cards diferentes para ingressos pagos e comprados
- Exibir dados do ingresso
- Exibir boleto caso não pago
- Melhorar dialog do QR Code
- Ver forma de agrupar ingressos da mesma festa

**Comment by AndreyLacerda** [comment]
pamps

**Comment by luis242** [comment]
pamps

**Comment by leaogui** [comment]
suave

**Comment by guga72** [comment]
safe.
