### ISSUE TITLE
Preparar apresentação do planejamento de PI2A6

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#430]

**Comment by AndreyLacerda** [comment]
[Uploading... documento_principal.pdf ]

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
Cara, tá mt bom, mas para mim faz mais sentido se os testos que falam sobre as "imagens" estivessem localizados depois das mesmas.

**Comment by guga72** [comment]
safe.
