### ISSUE TITLE
Adicionar mecânica de número de lote

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#438]
- Permitir lotes com mesmo nome, mas números diferentes e sequenciais
- Mostrar os lotes em sequencia na tela de venda
- Checar quando os lotes acabam, para nao mostrar e vender mais
- Proibir comprar mais ingresso do que está à disposição

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by tsmurer** [comment]
safe

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa
