### ISSUE TITLE
Desenvolver mecanismo de ingressos múltiplos no ``Meus Ingressos''

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#440]
- Checar QR Codes em cards com mais de um ingresso
- Checar boletos bancários

**Comment by AndreyLacerda** [comment]
- Deixar cards de ingressos com o mesmo tamanho
- É melhor o "Abrir QRCode" só aparecer em ingressos status_compra = 'P'
- Imprimir boleto não está funcionando
- Sugestão: Ao escolher o QRCode e o boleto, ao invés de usar o codIngresso, usar o nomeTitular no select

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by guga72** [comment]
safe.

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa
