### ISSUE TITLE
Aprimorar back-end de check-in

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#443]
- Fazer controller updateCheckin aceitar TO de ingresso com apenas codIngresso (pode ser por parâmetro tbm);
- Adicionar permissão para fazer check-in e receber o codUsuario via parâmetro, vendo se ele tem permissão para trabalhar no check-in;
- Colocar a dataCheckin e statusIngresso automaticamente quando der sucesso;
- Retornar erro bad request ao tentar fazer check-in em ingresso já checkados.

**Comment by AndreyLacerda** [comment]
Pamps.

**Comment by tsmurer** [comment]
safe

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa
