### ISSUE TITLE
Desenvolver envio de PDF dos relatórios por e-mail no back-end

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#479]
Receber codUsuario, codFesta, lista de e-mails e um PDF. Verificar permissão. Se OK, enviar o PDF para todos os e-mails da lista.

**Comment by Pedrofreitas18** [comment]
Agora uma permissão de exportar relatório, se não estiver associada ao grupo do id do usuário, vai dar merda

**Comment by luis242** [comment]
pamps

**Comment by leaogui** [comment]
pampa

**Comment by tsmurer** [comment]
pampa

**Comment by AndreyLacerda** [comment]
pampa

**Comment by guga72** [comment]
safe.
