### ISSUE TITLE
Corrigir bugs do front-end

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#497]
- usuario sem permissão
estoque: redireciona pro painel de cotnrole
segurança: 404
relatórios e ingresso: apresenta dialog de usuário sem permissão. porém, continua na página e pode manipular as funcionalidades.

- segurança: quando eu to sem as permissões de problemas de segurança, eu consigo visualizar os problemas, mas não consigo ver a imagem, finalizar ou marcar como engano.

- ingresso: sem a permissão de visualização de dados bancários, eu ainda consigo visualizar os dados bancários
não está aparecendo no front, mas estão cadastrados na tabela do banco (mesmo com permissão)

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by guga72** [comment]
safe.

**Comment by tsmurer** [comment]
okk
