### ISSUE TITLE
Documentar definição do escopo do projeto

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#5]

**Comment by luis242** [comment]
brabo. arrumei uma frase que me pareceu estranha.

**Comment by guga72** [comment]
Dei mais algumas arrumadas em algumas frases que me pareceram meio estranhas, mas agora parece bom.

**Comment by leaogui** [comment]
Por mim ta bom

**Comment by tsmurer** [comment]
Nice. Aprovado
