### ISSUE TITLE
Correção de bugs front-end v2

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#503]
- tela de integrações com Sympla/EventBrite não tem botão de retorno para página anterior
- quando não tiver camera falar que não ah tem ou coisa do genero
- erros que não foram cadastrados
- permissao que nao foi cadastrada

**Comment by luis242** [comment]
pamps

**Comment by Pedrofreitas18** [comment]
pampa

**Comment by tsmurer** [comment]
okk

**Comment by guga72** [comment]
safe.
