### ISSUE TITLE
Corrigir bugs Front-End identificados no Plano de Testes

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#508]
- TF85 - Falha(2) - Quando não tem permissão, apresenta o erro de "Sem permissão". Porém, da erro 404 e não redireciona ao painel da festa. (ERRO NÃO ENUMERADO CORRETAMENTE - NÃO SEI QUAL Q ERA, MAS PROVAVELMENTE ESTÁ CORRIGIDO)
- TF07 - Falha(4) - Mensagem de erro incorreta (FEITO)
- TF14 - Falha(3) - Mensagem de erro incorreta(FEITO)
- TF15 - Falha(3) - Mensagem de erro incorreta(FEITO)
- TF78 - Falha(3) - Está redirecionando o usuário para a index (FEITO)
- TF49 - Falha(1) - Redirecionando duas vezes e caindo no 404(FEITO)
- TF53 - Falha(1) - Redireciona para o 404 e nao avisa motivo(FEITO)
- TF57 - Falha(2) - Redireciona para o 404 e nao avisa motivo(FEITO)
- TF58 - Falha(2 e 4) - Redireciona para o 404 e nao avisa motivo(FEITO)
- TF59 - Falha(2 e 3) - Redireciona para o 404 e nao avisa motivo(FEITO)
- TF61 - Falha(2) - Não exibe mensagem de error corretamente(FEITO)
- TF21 - Falha(3) - Mensagem exibida está incorreta ("Os dados da festa não podem ser editados enquanto ela está iniciada.")(FEITO)
- TF28 - Falha(5)- Mensagem de erro não encontrado é a mensagem genérica da Pachanga deveria ser algo como "Usuário não se encontra mais nesse grupo" ou algo assim(FEITO - É O ERRO NA AÇÃO 3)
- TF42 - Falha(4) - mensagem mostrada é "Quantidade máxima inválida.", porém tem haver com a quantidade a quantidade atual(FEITO)
- TF88 - Falha(1) - Gif de loading travado (FEITO)
- TF89 - Falha(1) - Erro check-in qrcode sympla (FEITO)
- TF94/95 - Colocar qualquer URL quebra a tela de relatórios (FEITO)
- TF87 - Falha(2) - informa mensagem que deu merda, mas direciona para a 404 (FEITO)
- CORRIGIR CORS (FEITO)

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by guga72** [comment]
safe.

**Comment by leaogui** [comment]
samps

**Comment by tsmurer** [comment]
nice
