### ISSUE TITLE
Corrigir bugs Back-End identificados no Plano de Testes

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#509]
- TF20 - Falha(2) - Não existe permissão de alteração de status (FEITO)
- TF22 - Falha(2) - Não existe permissão de visualizar grupos de permissão (FEITO)
- TF24 - Falha(4) - Posso editar o nome de um grupo para um já existente (FEITO)
- TF38 - Falha(4) - É possível cadastrar produtos com o mesmo nome (FEITO)
- TF79 - Falha(Tudo) - Está dando problema de CORS (FEITO)
- TF38 - Falha(1) - Não está bloqueando a criação de produtos para pessoas que não tem essa permissão (FEITO)
- TF44 - Falha(2) - Permissão da baixa de produtos no estoque está ocorrendo pela permissão "Editar produto em estoque" (FEITO)
- TF45 - Falha(2) - Permissão da perda de produtos no estoque está ocorrendo pela permissão "Editar produto em estoque" (FEITO)
- TF46 - Falha(2) - Permissão da baixa de produtos por dose no estoque está ocorrendo pela permissão "Editar produto em estoque" (FEITO)
- TF47 - Falha(2) - Permissão de recarga de produtos no estoque está ocorrendo pela permissão "Editar produto em estoque" (FEITO)
- TF48 - Falha(?) - Permissão de recarga de produtos no estoque pela notificação está ocorrendo pela permissão "Editar produto em estoque" (FEITO)
- TF24 - Falha(2) - Consigo editar um grupo de permissão sem a permissão de editar (FEITO)
- TF22 - Falha(2) - Consigo criar um grupo de permissão sem a permissão de criar (FEITO)
- TF23 - Falha(2) - Consigo criar um grupo de permissão sem a permissão de criar (FEITO)
- TF25 - Falha(2) - Consigo excluir um grupo de permissão sem a permissão de excluir (FEITO)

**Comment by tsmurer** [comment]
very good well done congratulations

**Comment by AndreyLacerda** [comment]
Pamps
