### ISSUE TITLE
Desenvolver pendência back-end

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#511]
- Criar GET de Histórico de Segurança para os "Ver Mais"
- Salvar status da festa na notificação
- unificar categoria principal e secundária

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by leaogui** [comment]
Samps

**Comment by luis242** [comment]
paamps

**Comment by tsmurer** [comment]
okk
