### ISSUE TITLE
Desenvolver pendência front-end

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#512]
- alterar GET do "Ver Mais" de segurança para resgatar o histórico - FEITO
- Todos os botões inválidos devem ser cinza, não coloridos - FEITO
- notificação de status atualizando junto com o status da festa - FEITO
- adicionar ordenação fixa nas listas de estoque, area de segurança, produto, cupom, integracao, lote, google forms e festa - FEITO
- corrigir CSS da notificação de convite - FEITO
- corrigir mensagem da notificação de convite aceito - FEITO
- alterar mensagem de ingresso esgotado - FEITO
- alinhar telas de criação e edição de grupo de permissão - FEITO
- loading no envio de convite - FEITO
- caixa de escolhas de notificação bugada - FEITO
- alterar nome do PDF de relatório da festa - feito
- alterar dialog de boletos - FEITO
- retorno de categoria principal e secundária alterados - FEITO

**Comment by AndreyLacerda** [comment]
Pamps

**Comment by luis242** [comment]
pamps

**Comment by guga72** [comment]
safe.

**Comment by Pedrofreitas18** [comment]
okay
