### ISSUE TITLE
Fazer desenho do diagrama de atividades

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#6]

**Comment by luis242** [comment]
achei brabíssimo. luisin aproves.

**Comment by Pedrofreitas18** [comment]
No diagrama Adição de quantidade de produto ao estoque periférico é realizada uma redução. Gostei de como foram feitos os diagramas

**Comment by AndreyLacerda** [comment]
Corrigido

**Comment by leaogui** [comment]
se foi corrigido o que o pedro falou acho que ta pampa

**Comment by guga72** [comment]
Para mim está certo.

**Comment by tsmurer** [comment]
aprovado, vai pra done
