### ISSUE TITLE
Desenhar DER do banco de dados

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#7]

**Comment by AndreyLacerda** [comment]
editei umas coisas
falta colocar os formulários do google forms e os identificadores do facebook e google
ai organiza direitinho
tem q colocar nome nas relações e eu acho fortemente que as ordem dos índices das relações está ao contrário em muitos casos.

**Comment by leaogui** [comment]
pampa

**Comment by luis242** [comment]
boa cachorro.

**Comment by tsmurer** [comment]
aprovado guga
