### ISSUE TITLE
Documentar Gestão de tempo: Formato de Sprint

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#8]

**Comment by AndreyLacerda** [comment]
qual a periodicidade: 1 semana de sprint (Planejamento de Sprint as terças - as 19h(com suspensao) ou em aula(sem suspensao) / Revisão de sprint e retrospectiva da sprint são as segundas - as 19h(com suspensao) ou 21h(sem suspensao)), daily todo dia;

adaptações (como vai ser o Daily Scrum?) : Com suspensão das aulas - Daily no Discord todo dia as 19h. Sem suspensão de aulas, daily todo dias as 9h15min no intervalo da faculdade; Com suspensão, todas as reuniões serão Discord. Sem suspensão, o Planejamento de Sprint é na escola na aula de PI.

como são definidos os pesos por tarefas (poker, Fibonacci et cetera): Fibonacci (1, 2, 3, 5, 8, 13, 21{21 se for brutal}). Passando os cards um por um, cada integrante informa seu peso. O menor peso discute com o maior peso. O melhor argumento seta o peso no card.

ferramentas de controle usadas (p.e., gráficos de Burnout, Burnup, regras de teste, formato de Kanban): Kanban no Trello com as histórias de usuário, seguindo um path. Gráficos de Burndown, Cumulative Flow e Velocity Tracking. Explicar cada um imagens.

**Comment by AndreyLacerda** [comment]
Ae @Pedrofreitas18 , agora que eu percebi que o título do card tava errado, acho que isso confundiu. Não precisava falar tudo isso q tu falou, só falar como iria ser feita a gestão do tempo do projeto, ou seja, explicitar o formato da sprint (que deverá ser o nome da única subsection nessa parte). 
O Aires tinha passado no e-mail o q esse formato de sprint deveria ter, e a gente decidiu na quarta-feira (é o comentário grandão acima). Essa parte só precisa documentar o que a gente já tinha decidido, não precisa colocar tudo isso que tu colocou. 
Faz só o formato de sprint, e o resto que tu escreveu eu vou colocar na parte de metodologia de gestão aqui.

**Comment by tsmurer** [comment]
Ortograficamente tá 100%, se eu não deixei nada escorregar. Eu fiz uma única correção (tava escrito "na japão"). O conteúdo eu acho que também tá adequado ao que se espera, apesar de eu achar meio nebulosa a distinção entre os capítulos de gestão de tempo e metodologia de gestão.
Pra mim tá aprovado.

**Comment by AndreyLacerda** [comment]
Pra mim ta aprovado também.

**Comment by leaogui** [comment]
pampa

**Comment by luis242** [comment]
safe do safe.
