### ISSUE TITLE
Documentar possíveis design patterns à serem utilizados

### ISSUE THREAD

**Issue by luis242** [Projeto-Integrado-2020/Pachanga#9]

**Comment by leaogui** [comment]
Arrumei alguns erros, ta pampa por mim

**Comment by guga72** [comment]
Vi uns errinhos de português mudei e agora ta pampa.

**Comment by AndreyLacerda** [comment]
Revisei e corrigi algumas coisas. Agora tá bom pra mim.

**Comment by tsmurer** [comment]
gj luisão, to mandando pra done
