### ISSUE TITLE
Documentar o Diagrama de Atividades

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#92]

**Comment by Pedrofreitas18** [comment]
Top de mais. Por mim ta ok

**Comment by tsmurer** [comment]
Aprovado

**Comment by luis242** [comment]
brabo e aproved.

**Comment by guga72** [comment]
Tinha um só errinho no apêndice que era pra ser 6 em vez de 5, mas isso eu já arrumei então tá maravilhoso meu caro.

**Comment by leaogui** [comment]
Consertei alguns erros de escrita e adicionei algumas coisas, ta pampa

**Comment by leaogui** [comment]
Consertei alguns erros de escrita e adicionei algumas coisas, ta pampa
