### ISSUE TITLE
Documentar o MER (DER)

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#94]

**Comment by Pedrofreitas18** [comment]
O textinho está pampa, só 2 comentários: A imagem não está em um formato ok para ser impressa em uma folha sulfite, e cupom não deveria estar ligado com ingresso de alguma forma?

**Comment by leaogui** [comment]
Estamos resolvendo o problema com o tamanho, tudo vai dar certo com fé em deus

**Comment by AndreyLacerda** [comment]
ok

**Comment by tsmurer** [comment]
aprovado
