### ISSUE TITLE
Documentar os cenários

### ISSUE THREAD

**Issue by AndreyLacerda** [Projeto-Integrado-2020/Pachanga#97]

**Comment by AndreyLacerda** [comment]
Revisei, corrigi umas coisinhas. Pra mim ta bom. Eu tinha pensando em deixar só no apêndice, mas aquela tua introdução tá boa. deixa assim então.

**Comment by guga72** [comment]
Tá daora meu grande

**Comment by luis242** [comment]
achei mil grau.

**Comment by Pedrofreitas18** [comment]
Bem interessante o códico latex usado. Por mim tá ok

**Comment by leaogui** [comment]
Parte em apendices vão ser redirecionadas para o documento, aprovado
